### ISSUE TITLE
broken relational database diagram link?

### ISSUE THREAD

**Issue by neversummer17** [gwu-business/istm-4121#19]
When clicking on the link for sample relational database in the entity relationship diagramming assignment nothing appears, the link might not be properly assigned. This makes the assignment be unable to complete.

**Comment by s2t2** [comment]
this is what i see when i follow the link...

![screenshot 2015-10-05 16 12 58](https://cloud.githubusercontent.com/assets/1328807/10292227/11c049ac-6b7c-11e5-972e-b9ed3e9c7d80.png)

if you're referencing a broken image tag in that repository's README file, thanks for bringing it to my attention. I'm not sure why it's not embedding properly, but will look into posting a .png version of the image as well.
