### ISSUE TITLE
Syllabus

### ISSUE THREAD

**Issue by jordanmaidman** [gwu-business/istm-4121#30]
Would you be able to compile the syllabus in such a way that the weights of different assignments is clear?  

Is the project worth 50% of our grade?  What about the midterm/final?

**Comment by s2t2** [comment]
yes, the notation could be a bit more clear. refer to the [syllabus](https://github.com/gwu-business/istm-4121/blob/master/README.md#evaluation-methods) for the weight of each section.

each of two exams comprise 25% of the final grade. both exams together are worth 50% of the final grade.

the other 50% is comprised of the cumulative weight of all assignments. refer to the [assignments page](https://github.com/gwu-business/istm-4121/blob/master/ASSIGNMENTS.md) for the weights of each individual assignment. multiplication yields the final weight for each assignment.

for example, the group project assignment is worth 60% of the weight of all assignments, therefore the group project is worth 30% of your final grade.
