### ISSUE TITLE
data analysis 

### ISSUE THREAD

**Issue by neversummer17** [gwu-business/istm-4121#45]
Dear professor,

The comments below you left me on my data analysis lab, the only thing you really mention that is wrong is you cant find the dataset? But I uploaded the entire access dataset with my analysis to blackboard under this assignment. Please let me know what I can fix to achieve a better grade because I am very confused on your expectations. thank you

"good dataset identification but where can i find it?; good mention of factual findings at the beginning; insightful analysis; good statement of assumptions; good use of sql; could benefit from the use of aggregate sql clauses and functions"

**Comment by s2t2** [comment]
to address the question of dataset identification, I'm looking for the primary source, or where you got the data from (i.e. a URL to some data portal). 

to address need for aggregate clauses and functions, make sure to demonstrate proper use of a `GROUP BY` clause in conjunction with a `count()` or `sum()` or some other aggregate function.
